# The Phyton Standard Library

__Problem 1:__

In [3]:
 my_list = [1, 2, 3, 5, 6] 

In [4]:
min(my_list), max(my_list), sum(my_list)/len(my_list)

(1, 6, 3.4)

__Problem 2:__

In [5]:
#numbers --> immutable
x = 4
y = x
x +=1
x

5

In [6]:
y

4

In [7]:
#strings --> immutable                              example ; the variable, z, which points "Zehr" is immutable
z = "Zehr"                                       #z points "Zehr"
v = z                                            #v points the same "Zehr" that z points to
z += 'a'
print(z)

Zehra


In [8]:
print(v)

Zehr


In [9]:
#Lists -->  mutable
names = ["Ayse", "Rustem", "Cagin", "Cigdem"]
family_turk = names
family_turk.append("Zehra")
family_turk

['Ayse', 'Rustem', 'Cagin', 'Cigdem', 'Zehra']

In [10]:
names

['Ayse', 'Rustem', 'Cagin', 'Cigdem', 'Zehra']

In [ ]:
#tuples are immutable
my_tuple = (4, 5, 6)
my_tuple2 = my_tuple
my_tuple +=(1,)
my_tuple

In [12]:
#dictionaries are mutable
my_fave_food = {"fruits" : ["watermelon", "strawberry"],"vegetables" : "eggplant"}
my_fave_food2 = my_fave_food
my_fave_food[1]='a'
my_fave_food

{'fruits': ['watermelon', 'strawberry'], 'vegetables': 'eggplant', 1: 'a'}

In [13]:
my_fave_food2

{'fruits': ['watermelon', 'strawberry'], 'vegetables': 'eggplant', 1: 'a'}

In [7]:
#numbers --> immutable
#strings --> immutable 
#Lists -->  mutable
#tuples are immutable
#dictionaries --> mutable

__Problem 3:__

In [11]:
run calculator.py

What do you want to do(+,-,sqrt):+
Enter num1: 7
Enter num2: 8
15


In [12]:
def hypotenuse(a, b):
    return sqrt(a**2.0 + b**2.0)

In [13]:
hypotenuse(3,4) 

5.0

# Introduction to NumPy

__Problem 1:__

In [18]:
import numpy as np

In [19]:
A = np.array([[3,-1,4],[1,5,-9]]) #2X3 MATRIX

In [20]:
B = np.array([[2,6,-5,3],[5,-8,9,7],[9,-3,-2,-3]]) #3X4 MATRIX

In [21]:
np.dot(A,B)    #2X4 MATRIX

array([[ 37,  14, -32, -10],
       [-54,  -7,  58,  65]])

In [22]:
import numpy as np
np.ndarray?

__Problem 2:__

In [16]:
A = np.array([[3,1,4],[1,5,9],[-5,3,1]])

In [23]:
-(A**3) + 9*(A**2) - 15*A 

array([[   9,   25,   20],
       [  -7,   25, 1593]])

__Problem 3:__      #THIS IS EXTRA,  COULD BE IGNORED.

In [21]:
C = np.ones((7,7))

In [22]:
A = np.triu(C)

In [23]:
print(A)

[[ 1.  1.  1.  1.  1.  1.  1.]
 [ 0.  1.  1.  1.  1.  1.  1.]
 [ 0.  0.  1.  1.  1.  1.  1.]
 [ 0.  0.  0.  1.  1.  1.  1.]
 [ 0.  0.  0.  0.  1.  1.  1.]
 [ 0.  0.  0.  0.  0.  1.  1.]
 [ 0.  0.  0.  0.  0.  0.  1.]]


In [36]:
B = np.full((7,7), 5)

In [37]:
il1 = np.tril_indices(7) #Compute two different sets of indices to access 4x4 arrays,for the lower triangular part starting at the main diagonal

In [38]:
B[il1] = -1

In [39]:
B

array([[-1,  5,  5,  5,  5,  5,  5],
       [-1, -1,  5,  5,  5,  5,  5],
       [-1, -1, -1,  5,  5,  5,  5],
       [-1, -1, -1, -1,  5,  5,  5],
       [-1, -1, -1, -1, -1,  5,  5],
       [-1, -1, -1, -1, -1, -1,  5],
       [-1, -1, -1, -1, -1, -1, -1]])

In [43]:
matrix_product = A * B * A
matrix_product

array([[-1.,  5.,  5.,  5.,  5.,  5.,  5.],
       [-0., -1.,  5.,  5.,  5.,  5.,  5.],
       [-0., -0., -1.,  5.,  5.,  5.,  5.],
       [-0., -0., -0., -1.,  5.,  5.,  5.],
       [-0., -0., -0., -0., -1.,  5.,  5.],
       [-0., -0., -0., -0., -0., -1.,  5.],
       [-0., -0., -0., -0., -0., -0., -1.]])

In [44]:
matrix_product = matrix_product.astype(np.int64)
matrix_product

array([[-1,  5,  5,  5,  5,  5,  5],
       [ 0, -1,  5,  5,  5,  5,  5],
       [ 0,  0, -1,  5,  5,  5,  5],
       [ 0,  0,  0, -1,  5,  5,  5],
       [ 0,  0,  0,  0, -1,  5,  5],
       [ 0,  0,  0,  0,  0, -1,  5],
       [ 0,  0,  0,  0,  0,  0, -1]], dtype=int64)

__Problem 5:__

In [24]:
A = np.array([[0,2,4],[1,3,5]])    #2X3 MATRIX
E = np.transpose(A)
D = np.full((3,3),3)               #3X3 MATRIX
B = np.tril(D)                     #3X3 MATRIX
C = np.diag([-2,-2,-2])
F = np.zeros((3, 3))
G = np.zeros((2, 2))
I = np.ones((3,3))
H = np.zeros((2,3))
J = np.zeros((3,2))

In [25]:
M = np.bmat( [[F , E , I], [A ,G, H], [B , J , C]] )

In [26]:
M

matrix([[ 0.,  0.,  0.,  0.,  1.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  2.,  3.,  1.,  1.,  1.],
        [ 0.,  0.,  0.,  4.,  5.,  1.,  1.,  1.],
        [ 0.,  2.,  4.,  0.,  0.,  0.,  0.,  0.],
        [ 1.,  3.,  5.,  0.,  0.,  0.,  0.,  0.],
        [ 3.,  0.,  0.,  0.,  0., -2.,  0.,  0.],
        [ 3.,  3.,  0.,  0.,  0.,  0., -2.,  0.],
        [ 3.,  3.,  3.,  0.,  0.,  0.,  0., -2.]])

# Object Oriented Programming 

 __Problem 1:__

In [4]:
class Backpack(object):      
    def __init__(self, name, color, max_size = 5):      #this function is constructor. We make max_size default value 5.
        self.name = name
        self.contents = []
        self.color = color
        self.max_size = max_size 
        
    def put(self, item):       #we make sure that backpack doesn't go over capacity
        if len(self.contents) >= self.max_size:
            print("No Room!")
        if len(self.contents) < self.max_size:
            self.contents.append(item)
            
    def take(self, item):
        self.contents.remove(item)
        
    def dump(self):    #new method dump which resets the contents of the backpack to an empty list
        self.contents = []

__testing methods in the Backpack class:__

In [5]:
testpack = Backpack("Zehra", "green")    #instantiate an object (testpack) using Backpack class
for item in ["pencil", "pen", "paper", "computer", "eraser", "book"]:    #trying to put 6 items in the list
    testpack.put(item)
print(testpack.contents)

No Room!
['pencil', 'pen', 'paper', 'computer', 'eraser']


In [6]:
testpack.take('paper')   #remove an item
print(testpack.contents)

['pencil', 'pen', 'computer', 'eraser']


In [7]:
testpack.take('computer')
print(testpack.contents)

['pencil', 'pen', 'eraser']


In [9]:
testpack.dump()   #reset the contents of testpack

# __problem 2__:

In [11]:
class Backpack(object):
    def __init__(self, name, color, max_size = 5):   #constructor
        self.name = name
        self.contents = []
        self.color = color
        self.max_size = max_size 
        
    def put(self, item):
        if len(self.contents) >= self.max_size:
            print("No Room!")
        if len(self.contents) < self.max_size:
            self.contents.append(item)
            
    def take(self, item):
        self.contents.remove(item)
        
    def dump(self):
        self.contents = []

In [13]:
class jetpack(Backpack):
    def __init__(self, name, color, max_size = 2, fuel = 10):    #overwrite the constructor
        Backpack.__init__(self, name, color, max_size)
        self.fuel = fuel
        
    def fly(self, fuel_burned):
        self.fuel_burned = fuel_burned
        if self.fuel_burned <= self.fuel:
            self.fuel = self.fuel - self.fuel_burned
        if self.fuel_burned > self.fuel:
            print("Not Enough Fuel!")
           
            
    def dump(self):
        Backpack.dump(self)
        self.fuel = 0

__testing methods in the Backpack class:__

In [14]:
test_jetpack = jetpack("Zehra", "Green")

test_jetpack.put("computer")
print(test_jetpack.contents) 


['computer']


In [15]:
print(test_jetpack.fuel)

10


In [17]:
test_jetpack.dump()
print(test_jetpack.contents) 

[]


In [18]:
print(test_jetpack.fuel) 

0
